### ISSUE TITLE
Windows install?

### ISSUE THREAD

**Issue by BranchieManchie** [mathialo/bython#25] opened 2018-10-22 16:26 UTC
I'm trying to install Bython on windows with Python 3.7.1, by using `pip install bython` in the Windows admin command prompt. Pip reports it as installed, but the command prompt won't recognize the `bython` 
command. Am I doing something wrong?

**Comment by mathialo** [comment] 2018-10-30 14:41
Even though this is not a duplicate of [Issue 22](https://github.com/mathialo/bython/issues/22), I think it's common enough to close this isssue and focus on the other one. 

Another user submitted a workaround using the git bash shell. I suspect the same trick will work with the [Linux subsystem for Windows](https://docs.microsoft.com/en-us/windows/wsl/install-win10). For now, this is how to solve this issue, but feel free to look into the issue further. A proper Windows installer would of course be desirable.

**Closed by mathialo** 2018-10-30 14:41 UTC
