### ISSUE TITLE
IDE integration

### ISSUE THREAD

**Issue by intercepted16** [mathialo/bython#53] opened 2024-08-25 04:37 UTC
Please add integration with IDE's such as JetBrains. And code editors such as VS Code.
Please, please. Then I could actually use it. I love it.

**Comment by ShakalnyKot** [comment] 2024-08-29 02:21
> Then I could actually use it.

why does you need that so hard?

**Comment by intercepted16** [comment] 2024-08-29 02:23
@ShakalnyKot So that I don't have 500 errors showing up in my IDE.

**Comment by ShakalnyKot** [comment] 2024-08-29 02:27
> @ShakalnyKot So that I don't have 500 errors showing up in my IDE.

the errors will popup anyway in compile time or runtime, so you will not avoid it

**Comment by intercepted16** [comment] 2024-08-29 06:34
what do you mean? I can convert it with `by2py`
but ideally I should be able to write `.by` code with IDE support

**Comment by lolouthefox** [comment] 2024-09-01 18:29
> > @ShakalnyKot So that I don't have 500 errors showing up in my IDE.
> 
> the errors will popup anyway in compile time or runtime, so you will not avoid it

I think he's talking about the fact that the IDE thinks that the brackets are not supposed to be here and shows a squiggly red line.
![image](https://github.com/user-attachments/assets/ac4a19a9-684b-4722-8d03-b4fc2800f6ff)
I agree with @intercepted16, there probably should be IDE integration using a plugin, mostly for PyCharm and VSCode as they are the most used softwares.

**Comment by lolouthefox** [comment] 2024-09-01 18:31
But it's a duplicate of #32 actually

**Comment by intercepted16** [comment] 2024-09-01 22:18
Yeah, just realised it's a duplicate. Closing the issue now.

**Closed as completed** 2024-09-01 22:18 UTC
